# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute re Q for different values of tau2
#' 
#' @param x1 the effect size g in the unsplit leaves
#' @param x2 the sampling variance vi in the unsplit leaves
#' @param x3 the labels of nodes in the unsplit leaves
#' @param x4 tau2
#' @param x5 the effect size g in the parent leaf
#' @param x6 the sampling variance vi in the parent leaf
#' @param xuni the unique labels in the unsplit leaves
compute_re_Q_ <- function(x1, x2, x3, x4, xuni, x5, x6) {
    .Call('_metacartv2_compute_re_Q_', PACKAGE = 'metacartv2', x1, x2, x3, x4, xuni, x5, x6)
}

#' Compute tau2 
#' 
#' @param x1 the effect size g in the unsplit leaves
#' @param x2 the sampling variance vi in the unsplit leaves
#' @param x3 the lable of the unsplit leaves
#' @param x4 the sorted effect size in the parent leaf
#' @param x5 the sorted sampling variance in the parent leaf
#' @param xuni the unique labels in the unsplit leaves
compute_tau_ <- function(x1, x2, x3, xuni, x4, x5) {
    .Call('_metacartv2_compute_tau_', PACKAGE = 'metacartv2', x1, x2, x3, xuni, x4, x5)
}

#' Test if x1 contains the first element of x2 
#' 
#' @param x1 a charactor vector
#' @param x2 a charactor vector
contain_ <- function(x1, x2) {
    .Call('_metacartv2_contain_', PACKAGE = 'metacartv2', x1, x2)
}

#' Partition the test set based on a trained tree
#' 
#' @param x1 the tree component of the REmrt object
#' @param x2 the moderators in the test set
#' @param x3 indicates whether a moderator is numeric or not
#' @param x4 the index vector of the spliting moderators
#' @param x5 the list of split points
#' @param x6 the moderators in the training set
partition <- function(x1, x2, x3, x4, x5, x6) {
    .Call('_metacartv2_partition', PACKAGE = 'metacartv2', x1, x2, x3, x4, x5, x6)
}

#' Compute the subgroup effect sizes
#' 
#' @param x1 the node labels for each study
#' @param y  the effect size
#' @param vi the sampling variance
#' @param tau2 the residual heterogeneity
ComputeY <- function(x1, y, vi, tau2) {
    .Call('_metacartv2_ComputeY', PACKAGE = 'metacartv2', x1, y, vi, tau2)
}

#' Predict effect size for the test set
#' 
#' @param x1 the list of subgroup means
#' @param x2 predicted subgroup membership for the test set
PredY <- function(x1, x2) {
    .Call('_metacartv2_PredY', PACKAGE = 'metacartv2', x1, x2)
}

#' Replace missing values by the overall weighted mean
#' 
#' @param x1 the two-column matrix of the indices of missing values
#' @param x2 the matrix of predicted y with missing values
#' @param y  the effect size
#' @param vi the sampling variance
#' @param tau2 the residual heterogeneity
ReplaceNA <- function(x1, x2, y, vi, tau2) {
    .Call('_metacartv2_ReplaceNA', PACKAGE = 'metacartv2', x1, x2, y, vi, tau2)
}

